# Generated by Django 6.0.1 on 2026-02-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='price',
        ),
        migrations.AddField(
            model_name='signup',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default='Unknown', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default='Unknown', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
