# Generated by Django 6.0.1 on 2026-01-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='menu/')),
                ('description', models.TextField(default='')),
                ('type', models.CharField(choices=[('Hot Coffee', 'Hot Coffee'), ('Cold Coffee', 'Cold Coffee'), ('Special Coffee', 'Special Coffee')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=10)),
            ],
        ),
    ]
